name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: windows-latest  # Or you can use ubuntu-latest for Linux environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Set your desired Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run SonarQube Scan
        uses: SonarSource/sonar-scanner-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: 'http://localhost:9000'
