name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever version you use

      - name: Install dependencies (backend)
        working-directory: ./backend
        run: npm install

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      # Optional: run tests and generate coverage
      # - name: Run tests and generate coverage
      #   working-directory: ./frontend
      #   run: npm test -- --coverage

      - name: Download SonarScanner
        run: |
          choco install sonarscanner --version=5.0.1.3006 -y
          RefreshEnv

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner
