name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install SonarScanner CLI
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=my-latest-project ^
            -Dsonar.sources=src ^
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
